#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export MANWIDTH=999
#export PATH="$PATH:./node_modules/.bin"
# eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

# Go
export GOPATH=$HOME/go
export PATH="$PATH:${GOPATH}/bin"
export GOPROXY="direct"
# export GOPROXY="https://${ARTIFACTORY_USER}:${ARTIFACTORY_APIKEY}@artifactory.persgroep.cloud/artifactory/api/go/go,https://proxy.golang.org,direct"
# export GONOSUMDB="persgroep.cloud/*"


# Java
export PATH="/Library/Java/JavaVirtualMachines/graalvm-ce-java11-22.3.1/Contents/Home/bin:$PATH"
export GRAALVM_HOME="/Users/lvansteenbergen/.sdkman/candidates/java/22.3.r19-grl"
export JAVA_HOME="/Users/lvansteenbergen/.sdkman/candidates/java/22.3.r19-grl"

# Python
export PATH="~/Library/Python/3.7/bin:$PATH"
export PATH="$HOME/.pyenv/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Path
export PATH="/usr/local/bin/:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.local/bin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export PATH=$HOME/.fnm:$PATH
export PATH="$HOME/.local/share/neovim/bin":$PATH
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/opt/:$PATH"


#ZCLI
# export AWS_CA_BUNDLE=/opt/homebrew/etc/ca-certificates/cert.pem;
# export NODE_EXTRA_CA_CERTS=/Users/lvansteenbergen/.zcli/zscaler_root.pem;

#ZSH
export SHOW_AWS_PROMPT=true

#FZF
# export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
#     --color=fg:#e5e9f0,hl:#81a1c1
#     --color=fg+:#e5e9f0,hl+:#81a1c1
#     --color=info:#eacb8a,prompt:#bf6069,pointer:#b48dac
#     --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b
#     --height 60%'