--require'lsp-settings'
--require'dap-settings'
--require'plugin-settings'
--require'lsp_config'
require 'lang.python-lsp'
require 'lang.efm-lsp'
require 'plugins.compe-config'
require 'plugins.treesitter-config'
require 'plugins.general'
require 'plugins.linter'
require 'plugins.telescope'
require 'key'
