--require'lsp-settings'
--require'dap-settings'
--require'plugin-settings'
require 'lang.python-lsp'
require 'lang.yaml-lsp'
require 'lang.go-lsp'
require 'plugins.completion'
require 'plugins.treesitter-config'
require 'plugins.general'
require 'plugins.linter'
require 'plugins.telescope'
require 'plugins.statusline'
-- require 'key'
